/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorMaestro;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

/**
 *
 * @author pablo
 */
public class IngresarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CambiarUsuario
     */
    public IngresarUsuario() {
        initComponents();
        setResizable(false);
        ejecutarCambioBoton.setEnabled(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuarioTextBox = new javax.swing.JTextField();
        contraseniaTextBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ejecutarCambioBoton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usuarioTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usuarioTextBoxKeyReleased(evt);
            }
        });

        contraseniaTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseniaTextBoxActionPerformed(evt);
            }
        });
        contraseniaTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contraseniaTextBoxKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Ingrese su usuario:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Ingrese su contraseña: ");

        ejecutarCambioBoton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ejecutarCambioBoton.setText("Iniciar Sesion");
        ejecutarCambioBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejecutarCambioBotonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Ingresar usuario de LinkedIn");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel4.setText("Verifique previamente que los datos introducidos sean correctos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ejecutarCambioBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(contraseniaTextBox)
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(usuarioTextBox)
                        .addGap(67, 67, 67))))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel4)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(contraseniaTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(ejecutarCambioBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contraseniaTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseniaTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseniaTextBoxActionPerformed

    private void ejecutarCambioBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejecutarCambioBotonActionPerformed
        String UsuarioTextBox = usuarioTextBox.getText().trim();
        String ContraseniaTextBox = contraseniaTextBox.getText().trim();
        
        WebDriver driver = new ChromeDriver(); 
        driver.get("https://www.linkedin.com/login");
        
        WebElement inputUser =  driver.findElement(By.id("username"));
        inputUser.sendKeys(UsuarioTextBox);

        WebElement inputPassword =  driver.findElement(By.id("password"));
        inputPassword.sendKeys(ContraseniaTextBox);

        inputPassword.sendKeys(Keys.ENTER);
        
        try {
            Thread.sleep(10 * 1000);
        } catch (InterruptedException e) {}
            
        if (driver.getCurrentUrl().equals("https://www.linkedin.com/feed/")){
            driver.quit();
            //System.out.println("Inicio de sesion correcto");

            if (ControladorMaestro.leerValorProperties("config.properties", "correo").equals(UsuarioTextBox) && ControladorMaestro.leerValorProperties("config.properties", "contrasenia").equals(ContraseniaTextBox)){
                //System.out.println("No se tienen que actualizar las cookies");    
            } else {
                //System.out.println("Las cookies se deben de actualizar");
                ControladorMaestro.modificarArchivoProperties("config.properties", "correo", UsuarioTextBox);
                ControladorMaestro.modificarArchivoProperties("config.properties", "contrasenia", ContraseniaTextBox);
                ControladorMaestro.escribirEnArchivoFechaActualMas10Dias();
            }
            
            PantallaPrincipal modal = new PantallaPrincipal();
            modal.setVisible(true);
            this.dispose();
        } else {
            driver.quit();
            //System.out.println("Inicio de sesion FALLIDO");  
            JOptionPane.showMessageDialog(this, "Error: Usuario y/o Contraseña incorrectos", "Error al iniciar sesión", JOptionPane.WARNING_MESSAGE);
            IngresarUsuario modal = new IngresarUsuario();
            modal.setVisible(true);
            this.dispose(); 
        }
    }//GEN-LAST:event_ejecutarCambioBotonActionPerformed

    private void usuarioTextBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuarioTextBoxKeyReleased
        this.verificarCamposTexto();
    }//GEN-LAST:event_usuarioTextBoxKeyReleased

    private void contraseniaTextBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contraseniaTextBoxKeyReleased
        this.verificarCamposTexto();
    }//GEN-LAST:event_contraseniaTextBoxKeyReleased

   
    public static void main(String args[]) {
        try {
            // Establece el look and feel predeterminado del sistema
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarUsuario().setVisible(true);
            }
        });
    }
    
    private void verificarCamposTexto() {
        String ContraseniaTextBox = contraseniaTextBox.getText().trim();
        String UsuarioTextBox = usuarioTextBox.getText().trim();
        

        // Verificar si algún campo de texto está vacío
        if (!UsuarioTextBox.isEmpty() && !ContraseniaTextBox.isEmpty()) 
        {
            ejecutarCambioBoton.setEnabled(true);
        } else {
            ejecutarCambioBoton.setEnabled(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contraseniaTextBox;
    private javax.swing.JButton ejecutarCambioBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField usuarioTextBox;
    // End of variables declaration//GEN-END:variables
}
