name: Upload coverage reports to Codecov

on:
  push:
    branches:
      - Implementacion-Multi-Colecciones  # Change this to your default branch if it's different

jobs:
  codecov:
    name: Upload Coverage Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
